apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service
        imagePullPolicy: Never
        env: 
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: db-user
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: db-password
        ports:
        - containerPort: 80
        